version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    environment:
      - TOOL_NODE_FLAGS: '--max-old-space-size=4800'

orbs:
  node: circleci/node@1.1.6

commands:
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1-all
          cache-key: package.json
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --ignore-scripts --no-progress

jobs:
  build:
    executor: node12
    steps:
      - checkout
      - install_deps

      - run: yarn lint:ci
      - run: yarn build
      - run: yarn test

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
